# -*- coding: utf-8 -*-
"""Matrioshka v3.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_488X5b392mSwYXwkR2dDjKlxapOLpVm
"""

!pip install --quiet gymnasium torch

import math
import random
import numpy as np
import gymnasium as gym
from gymnasium import spaces

import torch
import torch.nn as nn
import torch.optim as optim
from collections import deque
import matplotlib.pyplot as plt

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

class GeothermalEnv(gym.Env):
    """
    Geothermal-aware compute scheduling:
    - RL agent decides energy source for each compute job.
    - Geothermal well has finite extraction rate (bandwidth),
      but near infinite total energy over time (no solar intermittency).
    """

    def __init__(self, episode_length=60, max_rate=50.0, regen_rate=8.0,
                 battery_capacity_kwh=200.0, seed=0):
        super().__init__()
        np.random.seed(seed)
        random.seed(seed)

        self.episode_length = episode_length

        # geothermal model
        self.max_rate = max_rate         # max extraction rate per timestep
        self.regen_rate = regen_rate     # well thermal regeneration rate
        self.reservoir_heat = max_rate   # initial well heat level

        # battery
        self.battery_capacity = battery_capacity_kwh
        self.battery_kwh = battery_capacity_kwh * 0.3

        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Box(low=0, high=1, shape=(3,), dtype=np.float32)

        self.job = None
        self.t = 0

    def _sample_job(self):
        # Random kWh demand (jobs)
        return float(np.random.choice([10, 20, 30, 40, 60], p=[0.40,0.25,0.20,0.10,0.05]))

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        self.reservoir_heat = self.max_rate
        self.battery_kwh = self.battery_capacity * 0.3
        self.t = 0

        self.job = self._sample_job()
        return self._get_obs(), {}

    def _get_obs(self):
        # Normalize for neural network stability
        well_pct = min(1.0, self.reservoir_heat / self.max_rate)
        battery_pct = self.battery_kwh / self.battery_capacity
        job_norm = min(1.0, self.job / 60.0)
        return np.array([well_pct, battery_pct, job_norm], dtype=np.float32)

    def step(self, action):
        job_kwh = self.job
        terminated = False
        truncated = False
        reward = 0.0
        info = {"executed": False}

        # ACTION 0 — Use Geothermal
        if action == 0:
            if job_kwh <= self.max_rate:
                # Overdraw check → failure mode (thermal fatigue)
                if job_kwh > self.reservoir_heat:
                    reward -= 15.0  # thermal collapse
                else:
                    self.reservoir_heat -= job_kwh
                    reward += 4.0  # best case (green computing)
                    info["executed"] = True
            else:
                reward -= 10.0   # agent tried to extract more than max extraction rate

        # ACTION 1 — Use Battery
        elif action == 1:
            if job_kwh <= self.battery_kwh:
                self.battery_kwh -= job_kwh
                reward += 2.0  # good alternative
                info["executed"] = True
            else:
                reward -= 8.0

        # ACTION 2 — Use Grid (penalty, non-renewable)
        else:
            reward -= 5.0      # grid always available
            info["executed"] = True

        # Recharge geothermal reservoir (Earth heat replenishment)
        self.reservoir_heat = min(self.max_rate, self.reservoir_heat + self.regen_rate)

        # Battery trickle-charge from geothermal overage
        leftover = max(0.0, self.reservoir_heat - self.max_rate * 0.8)
        self.battery_kwh = min(self.battery_capacity, self.battery_kwh + leftover * 0.4)

        self.t += 1
        terminated = (self.t >= self.episode_length)

        self.job = self._sample_job()
        return self._get_obs(), reward, terminated, truncated, info

# Cell 3 - DQN components (kept simple and stable)
class ReplayBuffer:
    def __init__(self, capacity=20000):
        self.buf = deque(maxlen=capacity)

    def push(self, s,a,r,ns,d):
        self.buf.append((s,a,r,ns,d))

    def sample(self, batch_size):
        batch = random.sample(self.buf, batch_size)
        s,a,r,ns,d = map(np.array, zip(*batch))
        return s,a,r,ns,d

    def __len__(self):
        return len(self.buf)


class QNet(nn.Module):
    def __init__(self, input_dim, action_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, action_dim)
        )

    def forward(self, x):
        return self.net(x)


class DQNAgent:
    def __init__(self, state_dim, action_dim, device="cpu",
                 lr=1e-4, gamma=0.99, batch_size=64, buffer_size=20000, target_update=500):
        self.device = torch.device(device)
        self.q = QNet(state_dim, action_dim).to(self.device)
        self.target = QNet(state_dim, action_dim).to(self.device)
        self.target.load_state_dict(self.q.state_dict())
        self.opt = optim.Adam(self.q.parameters(), lr=lr)
        self.gamma = gamma

        self.batch_size = batch_size
        self.replay = ReplayBuffer(buffer_size)
        self.target_update = target_update
        self.steps = 0

        self.eps_start = 1.0
        self.eps_end = 0.05
        self.eps_decay = 10000

    def select_action(self, state, valid_actions=None, evaluate=False):
        eps_threshold = self.eps_end + (self.eps_start - self.eps_end) * math.exp(-1. * self.steps / self.eps_decay)
        self.steps += 1
        if evaluate or random.random() > eps_threshold:
            state_v = torch.tensor(state, dtype=torch.float32, device=self.device).unsqueeze(0)
            with torch.no_grad():
                qvals = self.q(state_v).cpu().numpy().flatten()
            if valid_actions is not None:
                # mask invalid actions (if provided) - but valid_actions is not necessary here
                mask = np.full_like(qvals, -1e9)
                mask[valid_actions] = 0.0
                qvals = qvals + mask
            return int(np.argmax(qvals))
        else:
            if valid_actions:
                return random.choice(valid_actions)
            return random.randrange(self.q.net[-1].out_features)

    def push(self, s,a,r,ns,d):
        self.replay.push(s,a,r,ns,d)

    def update(self):
        if len(self.replay) < self.batch_size:
            return None
        s,a,r,ns,d = self.replay.sample(self.batch_size)
        s = torch.tensor(s, dtype=torch.float32, device=self.device)
        a = torch.tensor(a, dtype=torch.long, device=self.device)
        r = torch.tensor(r, dtype=torch.float32, device=self.device)
        ns = torch.tensor(ns, dtype=torch.float32, device=self.device)
        d = torch.tensor(d, dtype=torch.float32, device=self.device)

        q_vals = self.q(s).gather(1, a.unsqueeze(1)).squeeze(1)
        with torch.no_grad():
            next_q = self.target(ns).max(1)[0]
            target = r + self.gamma * next_q * (1 - d)

        loss = nn.MSELoss()(q_vals, target)
        self.opt.zero_grad()
        loss.backward()
        self.opt.step()

        if self.steps % self.target_update == 0:
            self.target.load_state_dict(self.q.state_dict())

        return loss.item()

def train_geothermal(episodes=500):
    env = GeothermalEnv()
    agent = DQNAgent(env.observation_space.shape[0], env.action_space.n, device=device)

    rewards, invalid = [], []

    for ep in range(episodes):
        s, _ = env.reset()
        done = False
        ep_reward = 0
        invalids = 0

        while not done:
            action = agent.select_action(s)
            ns, r, done, _, info = env.step(action)

            if not info["executed"]:
                invalids += 1

            agent.push(s, action, r, ns, done)
            agent.update()

            ep_reward += r
            s = ns

        rewards.append(ep_reward)
        invalid.append(invalids)

        if ep % 25 == 0:
            print(f"Ep {ep}/{episodes} | reward={ep_reward:.1f} | invalid={invalids}")

    return rewards, invalid

r, inv = train_geothermal(episodes=400)

plt.figure(figsize=(10,4))
plt.plot(r)
plt.title("Reward over episodes (Geothermal)")
plt.grid()
plt.show()

plt.figure(figsize=(10,4))
plt.plot(inv)
plt.title("Invalid actions (Geothermal)")
plt.grid()
plt.show()