# -*- coding: utf-8 -*-
"""Matrioshka v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175fBBQLG4WNdAZgnnFvmLkCKD821yOlz
"""

import random
import math
import pandas as pd
import matplotlib.pyplot as plt

class ComputeNode:
    def __init__(self, name, max_power, base_temp, efficiency):
        self.name = name
        self.max_power = max_power          # Max power budget (Watts)
        self.current_power = 0              # Current power usage
        self.base_temp = base_temp          # Idle temperature
        self.temp = base_temp               # Dynamic temperature
        self.efficiency = efficiency        # Compute efficiency score (0-1)
        self.jobs_handled = 0

    def can_handle(self, job):
        return (self.current_power + job.power_req <= self.max_power) and (self.temp < 85)

    def assign_job(self, job):
        self.current_power += job.power_req
        self.temp += job.thermal_load
        self.jobs_handled += 1

    def cool_down(self):
        self.temp = max(self.base_temp, self.temp - 2)
        self.current_power = max(0, self.current_power - 5)

class Job:
    def __init__(self, id, power_req, thermal_load, priority):
        self.id = id
        self.power_req = power_req          # Power requirement
        self.thermal_load = thermal_load    # Heat generated
        self.priority = priority            # 1 (low) → 10 (high)

def score_node(node, job):
    if not node.can_handle(job):
        return -math.inf
    thermal_penalty = node.temp / 100
    power_penalty = node.current_power / node.max_power
    return node.efficiency - (thermal_penalty + power_penalty) * 0.5


def schedule_jobs(nodes, jobs):
    log = []

    for job in jobs:
        best = None
        best_score = -math.inf

        for node in nodes:
            s = score_node(node, job)
            if s > best_score:
                best_score = s
                best = node

        if best and best_score > -math.inf:
            best.assign_job(job)
            log.append((job.id, best.name, round(best_score, 3)))
        else:
            log.append((job.id, None, "REJECTED"))

        for node in nodes:
            node.cool_down()

    return log

# Create 3 compute nodes
nodes = [
    ComputeNode("Shell A", 120, 40, 0.92),
    ComputeNode("Shell B", 100, 30, 0.88),
    ComputeNode("Shell C", 140, 50, 0.95)
]

# Generate 10 random jobs
jobs = [Job(i, random.randint(10,50), random.uniform(1,5), random.randint(1,10)) for i in range(10)]

import pandas as pd
import random

# ---------------------------
# Node definitions (capacity)
# ---------------------------
nodes = {
    "Shell A": {"cpu_total": 100, "ram_total": 64, "cpu_used": 0, "ram_used": 0},
    "Shell B": {"cpu_total": 120, "ram_total": 96, "cpu_used": 0, "ram_used": 0},
    "Shell C": {"cpu_total": 80,  "ram_total": 48, "cpu_used": 0, "ram_used": 0},
}

# ---------------------------
# Generate random jobs (requirements)
# ---------------------------
jobs = []
for i in range(10):
    jobs.append({
        "job_id": i,
        "cpu_req": random.randint(5, 25),
        "ram_req": random.randint(2, 16)
    })

results = []

# ---------------------------
# Scheduling based on dynamic load
# ---------------------------
for job in jobs:
    best_node = None
    best_score = -1

    for node_name, node_info in nodes.items():
        cpu_remaining = node_info["cpu_total"] - node_info["cpu_used"]
        ram_remaining = node_info["ram_total"] - node_info["ram_used"]

        if job["cpu_req"] > cpu_remaining or job["ram_req"] > ram_remaining:
            continue

        score = (cpu_remaining / node_info["cpu_total"]) + (ram_remaining / node_info["ram_total"])

        if score > best_score:
            best_score = score
            best_node = node_name

    if best_node:
        nodes[best_node]["cpu_used"] += job["cpu_req"]
        nodes[best_node]["ram_used"] += job["ram_req"]

        results.append({
            "Job": job["job_id"],
            "CPU Required": job["cpu_req"],
            "RAM Required": job["ram_req"],
            "Assigned Node": best_node,
            "Score": round(best_score, 3)
        })
    else:
        results.append({
            "Job": job["job_id"],
            "CPU Required": job["cpu_req"],
            "RAM Required": job["ram_req"],
            "Assigned Node": "FAILED (No capacity)",
            "Score": None
        })

df = pd.DataFrame(results)
df

def analyze_simulation(log, nodes):
    total_jobs = len(log)
    assigned_jobs = sum(1 for entry in log if entry[1] is not None)
    rejected_jobs = total_jobs - assigned_jobs

    # Average score for assigned jobs only
    numeric_scores = [entry[2] for entry in log if isinstance(entry[2], float)]
    avg_score = round(sum(numeric_scores) / len(numeric_scores), 3)

    # Power usage and temperature
    total_power = sum(n.current_power for n in nodes)
    avg_temp = round(sum(n.temp for n in nodes) / len(nodes), 2)

    return {
        "Total Jobs": total_jobs,
        "Assigned Jobs": assigned_jobs,
        "Rejected Jobs": rejected_jobs,
        "Scheduling Success (%)": round((assigned_jobs / total_jobs) * 100, 2),
        "Average Efficiency Score": avg_score,
        "Final Total Power Consumption": total_power,
        "Average Temperature": avg_temp,
    }

# Call summary
summary = analyze_simulation(results, nodes)
summary

scores = [entry[2] for entry in results if isinstance(entry[2], float)]

plt.figure(figsize=(8,4))
plt.plot(scores, marker='o')
plt.title("Node Efficiency Score Across Scheduled Jobs")
plt.xlabel("Job ID")
plt.ylabel("Efficiency Score (higher = better)")
plt.grid(True)
plt.show()