# -*- coding: utf-8 -*-
"""Matrioshka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175fBBQLG4WNdAZgnnFvmLkCKD821yOlz
"""

import random
import math
import pandas as pd

class ComputeNode:
    def __init__(self, name, max_power, base_temp, efficiency):
        self.name = name
        self.max_power = max_power          # Max power budget (Watts)
        self.current_power = 0              # Current power usage
        self.base_temp = base_temp          # Idle temperature
        self.temp = base_temp               # Dynamic temperature
        self.efficiency = efficiency        # Compute efficiency score (0-1)
        self.jobs_handled = 0

    def can_handle(self, job):
        return (self.current_power + job.power_req <= self.max_power) and (self.temp < 85)

    def assign_job(self, job):
        self.current_power += job.power_req
        self.temp += job.thermal_load
        self.jobs_handled += 1

    def cool_down(self):
        self.temp = max(self.base_temp, self.temp - 2)
        self.current_power = max(0, self.current_power - 5)

class Job:
    def __init__(self, id, power_req, thermal_load, priority):
        self.id = id
        self.power_req = power_req          # Power requirement
        self.thermal_load = thermal_load    # Heat generated
        self.priority = priority            # 1 (low) → 10 (high)

def score_node(node, job):
    if not node.can_handle(job):
        return -math.inf
    thermal_penalty = node.temp / 100
    power_penalty = node.current_power / node.max_power
    return node.efficiency - (thermal_penalty + power_penalty) * 0.5


def schedule_jobs(nodes, jobs):
    log = []

    for job in jobs:
        best = None
        best_score = -math.inf

        for node in nodes:
            s = score_node(node, job)
            if s > best_score:
                best_score = s
                best = node

        if best and best_score > -math.inf:
            best.assign_job(job)
            log.append((job.id, best.name, round(best_score, 3)))
        else:
            log.append((job.id, None, "REJECTED"))

        for node in nodes:
            node.cool_down()

    return log

# Create 3 compute nodes
nodes = [
    ComputeNode("Shell A", 120, 40, 0.92),
    ComputeNode("Shell B", 100, 30, 0.88),
    ComputeNode("Shell C", 140, 50, 0.95)
]

# Generate 10 random jobs
jobs = [Job(i, random.randint(10,50), random.uniform(1,5), random.randint(1,10)) for i in range(10)]

# Run scheduler
results = schedule_jobs(nodes, jobs)

# Print results
df = pd.DataFrame(results, columns=["Job", "Assigned Node", "Score"])
df